config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: master
      repo: https://github.com/ARGOeu/argo-messaging.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.scarlet_unique_unicorn.sh
        container: qc.acc_coffee_humble_meerkat
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.celadon_driven_condor.sh
        container: qc.doc_pumpkin_resilient_hyena
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.chestnut_eccentric_pegasus.sh
        container: qc.doc_espresso_dizzy_meerkat
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.polar_scrappy_macaw.sh
        container: qc.doc_kiwi_ambitious_ibis
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sand_generous_catfish.sh
        container: qc.lic_obsidian_confident_kiwi
  QC.Met:
    repos:
      github.com/ARGOeu/argo-messaging cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hunter_carefree_axolotl.sh
        container: qc.met_mustard_content_wolverine
      github.com/ARGOeu/argo-messaging validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flamingo_courageous_stingray.sh
        container: qc.met_onyx_carefree_finch
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.peach_candid_angelfish.sh
        container: qc.sec_clementine_optimistic_kookaburra
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.silver_flexible_kangaroo.sh
        container: qc.sec_raspberry_empathetic_opossum
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.turquoise_hopeful_echidna.sh
        container: qc.sty_watermelon_relaxed_frog
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.polar_rugged_buffalo.sh
        container: qc.sty_cinnamon_devoted_hedgehog
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.walnut_organized_dugong.sh
        container: qc.sty_avocado_funny_vulture
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-messaging pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gray_warm_rabbit.sh
        container: qc.uni_sand_feisty_kirin
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.isabelline_thoughtful_weasel.sh
        container: qc.ver_chartreuse_fearless_toad
timeout: 5400
