config:
  credentials:
  - id: https://github.com/ARGOeu/argo-messaging.git
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/ARGOeu/argo-messaging:
      branch: master
      credential_tmp: true
      credentials_id: https://github.com/ARGOeu/argo-messaging.git
      repo: https://github.com/ARGOeu/argo-messaging.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.moss_upbeat_impala.sh
        container: qc.acc_zinnia_hardworking_gull
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-messaging find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.orchid_assured_gazelle.sh
        container: qc.doc_paprika_reckless_cobra
      github.com/ARGOeu/argo-messaging git:
        commands:
        - /usr/bin/env sh .sqa/script.cornflower_courageous_beaver.sh
        container: qc.doc_purple_energetic_seahorse
      github.com/ARGOeu/argo-messaging markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flax_amused_falcon.sh
        container: qc.doc_isabelline_worried_falcon
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-messaging licensee:
        commands:
        - /usr/bin/env sh .sqa/script.reef_humorous_wolverine.sh
        container: qc.lic_cinnabar_ardent_thrush
  QC.Met:
    repos:
      github.com/ARGOeu/argo-messaging cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.forest_forgiving_flounder.sh
        container: qc.met_dusk_diplomatic_jackal
      github.com/ARGOeu/argo-messaging validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.storm_tough_gerbil.sh
        container: qc.met_cinnabar_eccentric_octopus
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-messaging bandit:
        commands:
        - /usr/bin/env sh .sqa/script.mustard_wise_rhinoceros.sh
        container: qc.sec_echelon_scrappy_moose
      github.com/ARGOeu/argo-messaging gosec:
        commands:
        - /usr/bin/env sh .sqa/script.brown_insightful_kookaburra.sh
        container: qc.sec_flax_intuitive_grasshopper
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-messaging flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ultramarine_humorous_panther.sh
        container: qc.sty_amaranth_ambitious_vulture
      github.com/ARGOeu/argo-messaging jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.royal_restless_hyena.sh
        container: qc.sty_aquamarine_confused_dormouse
      github.com/ARGOeu/argo-messaging staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.tan_diplomatic_dormouse.sh
        container: qc.sty_thunder_feisty_tiger
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-messaging pytest:
        commands:
        - /usr/bin/env sh .sqa/script.powder_organized_lemur.sh
        container: qc.uni_clementine_enigmatic_warthog
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-messaging get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jet_diligent_gazelle.sh
        container: qc.ver_cerulean_focused_turtle
timeout: 5400
