services:
  qc.acc_thunder_bright_crane:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_dusk_cheerful_viper:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_horizon_determined_ostrich:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc/markdownlint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_turmeric_logical_sparrow:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.lic_butter_vibrant_eel:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-licensee:9.17.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.met_clementine_innocent_mandrill:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Met/cff-converter-python
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.met_pineapple_amiable_giraffe:
    command: sleep 6000000
    image: alpine:3.15.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sec_brown_flexible_ostrich:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sec/bandit
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sec_dahlia_ardent_hippopotamus:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sec/gosec
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_papaya_cranky_uakari:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sty/staticcheck
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_porcelain_careful_orangutan:
    command: sleep 6000000
    image: pipelinecomponents/flake8:0.19.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_rose_rustic_sphinx:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sty/jsonlint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.uni_cerulean_proactive_ostrich:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-pytest:7.1.3-alpha
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.ver_viridian_balanced_roadrunner:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Ver
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
